# Generated by Django 4.2.3 on 2023-07-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catgoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('essencial', models.BooleanField(verbose_name='default=False')),
                ('valor_Planejamento', models.FloatField(verbose_name='default=0')),
            ],
        ),
    ]
