# Generated by Django 4.2.3 on 2023-07-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('essencial', models.BooleanField(default=False)),
                ('valor_planejamento', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('Nu', 'Nubank'), ('CE', 'Caixa Econômica'), ('C6', 'C6 Bank'), ('Inter', 'Inter'), ('BR', 'Bradesco'), ('Santander', 'Santander'), ('Itaú', 'Itaú'), ('BB', 'Banco do Brasil'), ('Will', 'Will Bank')], max_length=20)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('valor', models.FloatField()),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
        migrations.DeleteModel(
            name='Catgoria',
        ),
    ]
