# Generated by Django 4.2.3 on 2023-07-09 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_categoria_conta_delete_catgoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
