# Generated by Django 4.2.3 on 2023-07-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_categoria_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='data_vencimento',
        ),
    ]
